name: EconomyBridgeV2
main: fr.moodcraft.bridge.Main
version: 1.0
api-version: 1.20

commands:
  priceupdate:
    description: Sync un prix
    usage: /priceupdate <item>

  ecoreload:
    description: Reload config économie
    usage: /ecoreload