name: EconomyBridge
main: fr.moodcraft.bridge.Main
version: 1.0
api-version: 1.20

depend: [Vault]

commands:
  prix:
    description: Ouvre le marché
    usage: /prix

  syncprix:
    description: Sync tous les shops
    permission: econ.admin

  trend:
    description: Voir tendance
    usage: /trend <item>

  ecoreset:
    description: Reset complet de l'économie
    permission: econ.admin

  banqueadmin:
    description: Banque admin
    permission: econ.admin

  ecotest:
    description: Test economie
    permission: econ.admin

permissions:
  econ.admin:
    description: Accès total à l'économie
    default: op

  econ.use:
    description: Utiliser le marché
    default: true

  ecoreload:
    description: Recharge complète de l'économie
    permission: op