name: Build EconomyBridgeV2

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      version:
        description: "Nom du build"
        required: false
        default: "manual"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone repo
        uses: actions/checkout@v4

      - name: ☕ Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🔧 Build Maven
        run: mvn clean package

      - name: 📦 Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: EconomyBridgeV2-${{ github.event.inputs.version }}
          path: target/*.jar