name: Build Plugin

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 🔐 Auth GitHub Packages
      - name: Setup Maven auth
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # 📦 DEPLOY QuickShop
      - name: Deploy QuickShop
        run: |
          mvn deploy:deploy-file \
          -Dfile=libs/QuickShop-Hikari.jar \
          -DgroupId=com.quickshop \
          -DartifactId=quickshop \
          -Dversion=1.0 \
          -Dpackaging=jar \
          -DrepositoryId=github \
          -Durl=https://maven.pkg.github.com/${{ github.repository }}

      # 📦 DEPLOY Skript
      - name: Deploy Skript
        run: |
          mvn deploy:deploy-file \
          -Dfile=libs/Skript.jar \
          -DgroupId=com.skript \
          -DartifactId=skript \
          -Dversion=1.0 \
          -Dpackaging=jar \
          -DrepositoryId=github \
          -Durl=https://maven.pkg.github.com/${{ github.repository }}

      # 🔨 BUILD
      - name: Build
        run: mvn clean package

      # 📦 Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: target/*.jar